-- vim.pack.add {'https://github.com/nvim-neorg/neorg'}
-- require('neorg').setup {
--     load = {
--         ['core.defaults'] = {},
--         ['core.concealer'] = {},
--         ['core.dirman'] = {
--             config = {
--                 workspaces = {
--                     notes = '~/notes',
--                 },
--                 default_workspace = 'notes',
--             },
--         },
--         ['core.summary'] = {},
--     },
-- }
--
-- vim.wo.foldlevel = 99
-- vim.wo.conceallevel = 2
